[package]
name = "slamburger"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "A simple, learnable SLAM library for WebAssembly"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nalgebra = "0.32.2"
